#!/usr/bin/env bash

lein build-site

git clone git@github.com:gratimax/gratimax.github.io .git-site
cd .git-site
git checkout master
cp -R ../resources/_public/* .
git add .
git commit -m "Update $(date)"
git push origin master
cd ../

rm -rf .git-site